scrape_configs:
  - job_name: 'bot_monitoring'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8092']
        labels:
          application: 'bot'

  - job_name: 'scrapper_monitoring'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8091']
        labels:
          application: 'scrapper'
