name: Scrapper CI

on:
  push:
    branches: [ "master"]
    paths:
      - 'scrapper/**'
  pull_request:
    branches: [ "master"]
    paths:
      - 'scrapper/**'

permissions:
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tinkoff-app
    steps:
      - name: Create
        uses: actions/checkout@v3

      - name: Set up java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven project
        run: mvn package -pl scrapper -am

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ghcr.io/${{ github.actor }}/scrapper . -f scrapper/Dockerfile

      - name: push image
        run: docker push ghcr.io/${{ github.actor }}/scrapper
  check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tinkoff-app
    steps:
      - uses: actions/checkout@v3
      - name: Check module
        run: mvn -pl scrapper -am checkstyle:check